using UnityEngine;

public class Item_Base : MonoBehaviour
{
    [SerializeField] protected bool IsGet;//æ“¾ó‘Ô
    [SerializeField] protected GameObject Getter;//æ“¾Ò

    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        //æ“¾ó‘Ô
        if (Getter != null)
        {
            //
            Destroy(this.gameObject);
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.GetComponent<PlayerController>() != null)
        {
            //ƒvƒŒƒCƒ„[‚È‚ç‰ñûó‘Ô‚É
            Getter = other.gameObject;
        }
    }
}
